export const MpqDecryptionTests = [
  {
    name: 'tableA',
    input:
      'W2NIPTTaCMqNVTb447FH6X8dP7akh8VkNgR/4uZkCz0K49H4mvy6jJaeI/m0VLqVkfwNEpdYeN067d3GJqtFnb+nA/tl1p1SAKRgi05uIQDSi6hgWUdo7zULcrExselXmYYoGmQ+8eh60G9BvMIaaHO6e2JfkBepVmQSseSJCtwY07W5yswXaolQGoKNh4c9QHyBswYYTa3Q70mR7nsztSGhqxA94kIdzPCnqsqhUQk+vt9tr2qEo+4MHOkqUM6CwvCh47qXeeFj7QVLxYRvpAvaaSk8ELZNykeB6YphVyLc7Z3JbkD5di00KitJ15MGwtEX4MVirGywVJI87NKIyYBAq69GiUqc+VKkCh9h2mk=',
    output:
      '0AQAAGUCAABlAgAAAAIAgUUHAAAfAgAAHwIAAAACAIF0CQAALgEAAEMCAAAAAgCBsgoAACQGAAA1DQAAAAIAgeYQAAA+BgAA6AwAAAACAIE0FwAAhU0AAGGQAAAAAgCB2WQAAPMWAAA4JwAAAAIAgdx7AAA4AAAAOAAAAAACAIEkfAAAKAAAADQAAAAAAgCBXHwAAHABAACuAQAAAAIAgQAAAAAAAAAAAAAAAAACAIDcfQAArxIAAMx+AAAAAgCBm5AAACgCAACxAwAAAAIAgdOSAACbAwAA2xQAAAACAIF+lgAADAAAAAwAAAAAAgCBmpYAALUAAABNAQAAAAIAgV+XAABcAQAAXAEAAAACAIE=',
    key: 0xec83b3a3,
  },
  {
    name: 'tableB',
    input:
      'Ygo1UN89fvcs2XvCVmEGtlBGhEnnwKMpeQ6UcHWi76wcTH+DZ/SxaBM6JLDJIIXu/HaW4y+f/bwPlRtG2B0X3l8pYlcMsc0JqzhYuVSJhbr63okln89wI/tRK2imNW+n4Y29K68wRkrPH/pFlgDH2cIPYSHB8L9vr50LLGsYWdcsveBF3ntvLcP6u9PwrmERD/NrsziQEPfZeX/hK87lPNOrgP2N1I0Ukwb57sud8/dUi/URBg8efOvyPPgYrAHGw6va6idpntcXvYqA5EZrZlvfiMSIJssbp10EC9BNtkFTjGcJqilIxQaqeusfj6mUqjuDZ8h/mTUQQpx672qtogoQidGQXyLjkikAfqAg32eLrJmkHVdGY+I9bsTvVVwY7nm7mffyUKd4NMyZqtzJ/m5BhNG/KAI5gX/5r3I0A9nbHvMObRPOGDKE7So/ZsROHeCkOMkLpb0RJE+JI428h+DRDnmtaQ9hbAXR+DXuF+l2l3IUaJ88zo2PLY763AUaWeKV0MJoeLmjY+LwNfGlOBWcW0euO8F30jZ2PeXVFhZGT2svOFFMSF17M0rKQslWKQLGpZKCrDRzt5nSBb9HUcqinHLXV1eM1rgWjd8OFAZgzfLQkpLDGvfnkmukQhakc7Llfsswobbr6Ns8N+3hrAqzV2Fjcty+ZTWAWdqmYLM=',
    output:
      'rsUJ1lnRqMoAAAAAAQAAAGTPaUyL40FgAAAAAAQAAAAJQvjByg1YQQAAAAAOAAAAS6XCqpUrdvQAAAAABgAAAP////////////////////9wt+XJtvYYOwAAAAAJAAAAewg8NII2jicAAAAACAAAAKAeKztX8C63AAAAAAwAAAD//////////////////////////////////////////5zCg9OSLkDvAAAAAAAAAAD/////////////////////C8Eu6YwgFEIAAAAAAgAAAP/////////////////////dmUR2sGEbawAAAAAFAAAAyzeE0+zq3wcAAAAAEAAAAOHXdC4QHieLAAAAAAoAAAD//////////////////////////////////////////57LGf5dcEBiAAAAAAsAAAD/////////////////////3It+Wlw/Jf8AAAAAAwAAAP///////////////////////////////////////////////////////////////xB5Zf2nmJtOAAAAAA8AAAD/////////////////////////////////////////////////////////////////////////////////////z7CoHSj/zqIAAAAADQAAAIkilTGj+l9qAAAAAAcAAAA=',
    key: 3283040112,
  },
];
